spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/socket?serverTimezone=Asia/Seoul # local DB
    username: root
    password: ashjya711
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql:
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secret: "2d8f1b9c7e3a4f6b9d1c2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b"
  access-expiration-time: 1800000
  refresh-expiration-time: 180000000
#logging:
#  level:
#    root: debug
